name: "Cache dependencies"
description: "Cache node_modules"
inputs:
  package-manager:
    description: "Package Manager"
    required: false
    default: yarn
  cache-version:
    description: "Cache version"
    required: false
    default: v1
  lock-file:
    description: "Lockfile name"
    required: true
    default: yarn.lock
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: "Get cache path"
      uses: AstrumU/shared-workflows/.github/actions/get-workspacefeature/KAN-264
      id: cache-path
      with:
        package-manager: ${{ inputs.package-manager }}

    - name: "Cache dependencies"
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ${{ steps.cache-path.outputs.dependency-cache-path }}
        key: ${{ runner.os }}-${{ inputs.package-manager }}-${{ inputs.cache-version }}-${{ hashFiles(format('{0}', inputs.lock-file)) }}
