name: "Cache build"
description: "Cache build artifacts"
inputs:
  package-manager:
    description: "Package Manager"
    required: false
    default: yarn
outputs:
  pnpm-build-cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.pnpm-build-cache.outputs.cache-hit }}
  yarn-build-cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.yarn-build-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    # - name: "Get lockfile"
    #   id: get-lockfile
    #   shell: bash
    #   run: |
    #     if [ ${{ inputs.package-manager }} == 'yarn' ]; then 
    #       echo "lock-file=yarn.lock" >> $GITHUB_OUTPUT
    #     else
    #       echo "lock-file=pnpm-lock.yaml" >> $GITHUB_OUTPUT
    #     fi

    - name: "Cache build"
      uses: actions/cache@v3
      if: inputs.package-manager == 'pnpm'
      id: pnpm-build-cache
      with:
        path: ./*
        key: build-${{ github.sha }}
     
    - name: "Cache build"
      uses: actions/cache@v3
      if: inputs.package-manager == 'yarn'
      id: yarn-build-cache
      with:
        path: |
          packages/**/dist
          packages/**/tsconfig.tsbuildinfo
        key: build-${{ github.sha }}
