name: "Install \ Restore dependencies"
description: Install or Restore yarn\pnpm dependencies
inputs:
  packageManager:
    description: "Package Manager"
    required: false
    default: yarn
  cacheVersion:
    description: "PNPM/YARN cache version"
    required: true
    default: v1

runs:
  using: composite
  steps:
    - name: Restore node_modules cache yarn
      id: yarn_cache
      if: inputs.packageManager == 'yarn'
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/**/node_modules
        key: ${{ runner.os }}-${{ inputs.cacheVersion }}-${{ hashFiles('yarn.lock') }}

    - name: yarn dependencies
      shell: bash
      if: ${{ inputs.packageManager == 'yarn' && steps.yarn_cache.outputs.cache-hit != 'true' }}
      run: ${{ inputs.packageManager }} install --frozen-lockfile --check-files --ignore-scripts

    - name: pnpm dependencies
      shell: bash
      if: inputs.packageManager == 'pnpm'
      run: ${{ inputs.packageManager }} install --frozen-lockfile
