name: 'Configure Environment'
description: 'Shared configuration for checkout, NodeJS and package manager'
inputs:
  nodeVersion:
    description: 'NodeJS Version to use'
    required: true
    default: ".nvmrc"
  packageManager:
    description: 'Package Manager'
    required: false
    default: yarn
  pnpmVersion:
    description: 'PNPM Manager version'
    required: false
    default: 7.13.3
  cacheVersion:
    description: 'PNPM/YARN cache version'
    required: false
    default: v11

runs:
  using: composite
  steps:
    - name: Setup ${{ inputs.packageManager }}
      id: pnpm_setup
      if: inputs.packageManager == 'pnpm'
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ inputs.pnpmVersion }}
        run_install: false

    - name: setup node
      uses: actions/setup-node@v3
      with:
       node-version-file: ${{ inputs.nodeVersion }}
       
    - name: Setup ${{ inputs.packageManager }}
      id: yarn_setup
      if: inputs.packageManager == 'yarn'
      shell: bash 
      run: npm i -g yarn 

    - name: Restore node_modules cache ${{ inputs.packageManager }}
      id: pnpm_cache
      if: inputs.packageManager == 'pnpm'
      uses: actions/cache@v3
      with:
          path: |
            node_modules
            packages/**/node_modules
          key: ${{ runner.os }}-${{ inputs.cacheVersion }}-${{ hashFiles('pnpm-lock.yaml') }}-test
          restore-keys: |
            ${{ runner.os }}-${{ inputs.cacheVersion }}-${{ hashFiles('pnpm-lock.yaml') }}-test

    - name: Restore node_modules cache ${{ inputs.packageManager }}
      id: yarn_cache
      if: inputs.packageManager == 'yarn'
      uses: actions/cache@v3
      with:
          path: |
            node_modules
            packages/**/node_modules
          key: ${{ runner.os }}-${{ inputs.cacheVersion }}-${{ hashFiles('yarn.lock') }}-test
          restore-keys: |
            ${{ runner.os }}-${{ inputs.cacheVersion }}-${{ hashFiles('yarn.lock') }}-test

    - name: yarn install
      shell: bash
      if: ${{ inputs.packageManager == 'yarn' && steps.yarn_cache.outputs.cache-hit != 'true' }}
      run: yarn install --frozen-lockfile --check-files --ignore-scripts

    - name: pnpm install
      shell: bash
      if: ${{ inputs.packageManager == 'pnpm' && steps.pnpm_cache.outputs.cache-hit != 'true' }}
      run: pnpm install --frozen-lockfile
