on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: ".nvmrc"
      name:
        required: false
        type: string
      packageManager:
        type: string
        required: false
        default: yarn
      cacheVersion:
        type: string
        required: true
        default: v1
      pnpmVersion:
        type: string
        required: false
        default: 7
      nodeOptions:
        type: string
        required: false
        default: "--max_old_space_size=8192"
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  test-unit-server:
    runs-on: self-hosted

    steps:
      - uses: AstrumU/shared-workflows/setup@fix/KAN-242
        name: Setup env
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          packageManager: ${{ inputs.packageManager }}
          cacheVersion: ${{ inputs.cacheVersion }}
          pnpmVersion: ${{ inputs.pnpmVersion }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NODE_OPTIONS: ${{ inputs.nodeOptions }}

      - name: Install dependencies
        uses: AstrumU/shared-workflows/dependencies@fix/KAN-242
        with:
          packageManager: ${{ inputs.packageManager }}
          cacheVersion: ${{ inputs.cacheVersion }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NODE_OPTIONS: ${{ inputs.nodeOptions }}

      - uses: actions/cache@v3
        id: build-cache
        name: Cache
        with:
          path: |
            packages/**/dist
            packages/**/tsconfig.tsbuildinfo
          key: ${{ github.sha }}

      - name: Unit tests server
        run: yarn test:unit:server --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NODE_OPTIONS: ${{ inputs.nodeOptions }}
